### PR TITLE
Asset page filtering

### PR DESCRIPTION
**Pull request by d-bucur**
WIP for Issue #450 

I created a search bar that can filter cards in JS. The problem is that the cards are in a `grid` and when setting `display:none` it will leave around empty spaces. The only way I see to do it properly would be to change the display of the cards to `flex-row` instead of `grid` (which I think makes more sense for this layout anyway), but that requires quite a bit of work making sure everything is responsive and that there are no regressions.

image

Result when searching for "MIT"

image

Any thoughts on this?

### CODE REVIEW

**Comment by d-bucur** [comment]
Nevermind, setting display:none on grid elements does work properly, I was just doing it on the wrong element. So no need for big changes. Will update with images soon.

**Comment by d-bucur** [comment]
And it's ready. Terms are separated by space and put in AND. Feedback welcome.

[Screencast from 22-08-2023 22:44:09.webm](https://github.com/bevyengine/bevy-website/assets/6576777/fc219a92-2714-47cb-b726-f132d44e33de)

**Review by cart — APPROVED** [review]
This is a solid win. Well done!

**Comment by cart** [comment]
(I removed the submodule that you added)

**Comment by d-bucur** [comment]
Thanks! Didn't notice that submodule slip by

**Pull request merged**
