### PR TITLE
Roids Sponsor Section

### PR DESCRIPTION
**Pull request by Braymatter**

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Thanks!

image

**Comment by cart** [comment]
Just made the gold fit in with the other metal colors (by desaturating a bit). I also gave the logo a manual size override to make it a bit bigger (we do this when the default height doesn't provide equal "size prominence" for a logo relative to others)

**Review by cart — APPROVED** [review]

**Comment by Braymatter** [comment]
Sweet, thanks! I just picked the first gold hex value I found.

**Comment by cart** [comment]
Thanks for your support!

**Pull request merged**
