### PR TITLE
Properly handle plurals and code blocks

### PR DESCRIPTION
**Pull request by mattfbacon**
For a type called `App` that is plural, it should look like this:

> `App`s

and not

> `Apps`

because the latter makes it sound like a singular type named "Apps".

### CODE REVIEW

**Comment by mattfbacon** [comment]
I don't think that CI failure has anything to do with my change

**Comment by cart** [comment]
I think the resulting styling here is too awkward / degrades perceived quality too much:

image

* The spacing between `App` and the `s` is too separate (due to the padding)
* The `s` takes on the "link styling" which feels out of place.

I'm on board for a change like this, but I think it should attempt to re-color the `s` to something more natural (maybe as the "normal text" white) without adjusting spacing.

**Comment by mattfbacon** [comment]
I wouldn't want to rely on color alone to indicate important semantic differences for accessibility reasons. Ideally, only actual code should be inside a `<code>` tag.

For my initial solution I valued simple markup—what you'd get if you did it in Markdown, like ``[`App`s](https://example.com/struct.App.html)``.

> The s takes on the "link styling" which feels out of place.

To address this specifically, would taking the S out of the `<a>` tag work?

**Comment by cart** [comment]
At that point I think we should just remove `plural = true` entirely in favor of tacking manual `s` on things. Thats ok with me.

**Comment by mattfbacon** [comment]
I made this change. However, it seems that either Zola or Tera is injecting an unwanted space (or maybe newline?) between the shortcode and the `s` that is directly after it in the markup. Not sure how to suppress this.

**Review by cart — APPROVED** [review]
Turns out the newline in the shortcode was resulting in the extra space :)

**Comment by mattfbacon** [comment]
Wow, that should be considered a bug in whatever relies on that. A string of characters that doesn't end in a newline is not a line after all

**Comment by mattfbacon** [comment]
For example Neovim fixes the line if you even touch the file.

**Pull request merged**
