### PR TITLE
reuse code blocks from validated crate

### PR DESCRIPTION
**Pull request by mockersf**
sister PR to #148: the same thing, but with a crate that can be compiled, and code blocks included from that crate

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
@cart can we merge this or #148 so I can use it in #176 and its siblings?

**Comment by cart** [comment]
Sure. I'll resolve conflicts

**Comment by cart** [comment]
Heads up that we'll probably want to add support for configuring "file code block indents"
image

This could probably just be another `indent=4` parameter in the shortcode

**Comment by cart** [comment]
Hmm i tried my hand at indents and so far no dice. No number of indents (either spaces or tabs) indents the code block as a whole (it just indents the interior code block). Also tried changing `markdown(inline=true)` to false.

```html
{% if not lang %}
    {% set lang = "" %}
{% endif %}

{% if not indent %}
    {% set indent = 0 %}
{% endif %}

{% set_global indent_str = "" %}
{% for i in range(end = indent) %}
    {% set_global indent_str = indent_str ~ " " %}
{% endfor %}

{% set code = load_data(path=path) %}

{% if anchor %}

    {% set code_lines = code | split(pat="\n") %}
    {% set code = "" %}
    {% set in_anchor = false %}

    {% for line in code_lines %}

        {% if line is ending_with("// ANCHOR_END: " ~ anchor) %}
            {% set_global in_anchor = false %}
        {% endif %}

        {% if in_anchor %}
            {% set_global code = indent_str ~ code ~ line ~ "
" %}
        {% endif %}

        {% if line is ending_with("// ANCHOR: " ~ anchor) %}
            {% set_global in_anchor = true %}
        {% endif %}

    {% endfor %}

{% endif %}

{% set data =  indent_str ~ "```" ~ lang ~ "
" ~ code ~ indent_str ~ "```" %}

{{data | markdown(inline=true) | safe}}
```

**Comment by cart** [comment]
I do want to make this work first if possible. Without it we'll have ugly formatting in a number of places. I've gotta go back to renderer stuff for now. Lemme know if any of you can get this operational :)

**Comment by mockersf** [comment]
#203 was chosen instead

**Pull request closed without merging**
