### PR TITLE
[Merged by Bors] - Add Examples to nav and add "intro" text

### PR DESCRIPTION
**Pull request by cart**
I think we've ironed out enough of the kinks to justify making the examples page more prominent. We've been sitting on a lot of value here for awhile :smile: 

For posterity: big thanks to @mockersf for putting together this feature in #225 and @doup for adding loading feedback in #355 and a bunch of other visual improvements.

### CODE REVIEW

**Review by IceSentry — APPROVED** [review]
Not sure if we want to keep it in the learn section if it's already in the header, but other than that I tried it locally and it looks good.

**Comment by alice-i-cecile** [comment]
I'm on board with this choice :)

**Review by mockersf — APPROVED** [review]

**Comment by cart** [comment]
> Not sure if we want to keep it in the learn section if it's already in the header, but other than that I tried it locally and it looks good.

I think we probably do as we don't want people to accidentally miss the examples when looking for learning material.

**Pull request closed without merging**
