### PR TITLE
Increase footer gap

### LINKED ISSUE #1862: Increase the social footer links gap slightly
It's a wee bit close together, but it shouldn't be widened too much.

Just need to change this value:

https://github.com/bevyengine/bevy-website/blob/main/sass%2Fcomponents%2F_footer.scss#L6

### PR DESCRIPTION
**Pull request by bienjensu**
Increases the footer gap from 10px to 25px.

Fixes #1862

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Can you include a screenshot of what this looks like now for reviewers?

**Comment by TrialDragon** [comment]
The PR result should look like this I think:

after

Compared to before:

before

**Comment by TrialDragon** [comment]
Mobile after:
image
Mobile before:
image

**Comment by cart** [comment]
I'm cool with the new spacing. But I think it has increased the prominence slightly and it was already too prominent. I'm thinking maybe we should make them smaller and a bit gray-er. But that can happen later.!

**Review by cart — APPROVED** [review]

**Pull request merged**
