### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by godsmith99x**
Adds a note on necessary package dependencies for Fedora 35 users.

### CODE REVIEW

**Comment by rparrett** [comment]
Totally agree that dependencies should be mentioned prior to telling folks to run the examples. They are mentioned on the [next page](https://bevyengine.org/learn/book/getting-started/setup/), which links to [linux_deendencies.md](https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md).

If I recall correctly, though, this isn't an issue in the new welcome chapter of the book being worked on [here](https://github.com/bevyengine/bevy-website/pull/176).

**Comment by rparrett** [comment]
It looks like `rust-libudev-devel` isn't mentioned there though, so a PR on the bevy repo adding that would probably be welcome!

**Comment by cart** [comment]
Yeah I dont think duplicating platform-specific dependencies in the welcome chapter is worth the maintenance cost (or the bloat ... there are a lot of platform specific notes). The linux_dependencies.md file is where this type of content should live. Definitely happy to revisit how / where we link to that doc though. Maybe sync up with @alice-i-cecile on the "new bevy book" currently in development?

**Comment by godsmith99x** [comment]
Cool. That all makes sense. Thanks for the review!

**Pull request closed without merging**
