### PR TITLE
Show feature image next to text

### LINKED ISSUE #308: Compress Feature page layout
The current feature page shows a lot of good stuff, but it requires a whole lot of scrolling. We could pretty easily put the images showcasing a feature to the left or right of the text to be able to fit a lot more stuff on the page.

https://amethyst.rs is a decent example of what I'm suggesting.

image

https://godotengine.org does it a bit differently, but it has multiple feature on each line so it's still more compressed than us.

image

### PR DESCRIPTION
**Pull request by IceSentry**
So that was pretty easy. Everything was already setup correctly except that the max-width was slightly too wide to allow flex to do it's thing and show the features side by side.

I also moved the image for the cross platform section inside the container.

image

Closes #308

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Pretty! Can you get a new screenshot with "Features" removed?

**Comment by IceSentry** [comment]
I updated the screenshot

**Comment by IceSentry** [comment]
I made a small change to how we do this. Instead of relying on adding a container-reverse class manually I used the css selector `::nth-child(odd)` which will apply the `flex-reverse` property automatically on each odd children.

**Comment by rparrett** [comment]
What sort of device are you testing with?

Both `28rem` and `30rem` seem pretty arbitrary to me, and I have always experienced the features page as "alternating side by side."

But I don't think that this makes the images too small, and if there's some common screen size that now displays the page side-by-side then that's good.

**Comment by IceSentry** [comment]
Interesting, I'm just using an old 1080p desktop monitor and I also tried it on a 1440p ultrawide monitor and they both show everything lineraly like this:

image

I haven't tried it in other browsers though.

I agree that the numbers seem arbitrary. I tried a few combinations and 28 was the one that worked.

There's a different approach that uses float left/right instead of using flex and hoping it wraps correctly.

**Comment by IceSentry** [comment]
Oooh, interesting, so in edge and firefox it does work correctly without any changes.

**Comment by IceSentry** [comment]
Chrome seems fine too...

**Comment by IceSentry** [comment]
Alright, found the issue. Apparently my default font size was set to 18 instead of 16 which just broke everything.

**Comment by alice-i-cecile** [comment]
@IceSentry what do you think we should do with this pr now that you've tracked down the root cause?

**Comment by IceSentry** [comment]
Well, I'm trying to find ways that don't rely on a width proportional to the font size. It makes sense sometimes, but I'm not sure it's the best approach here.

There's an option to use float left and float right, but it doesn't adjust correctly on mobile.

Technically, this PR also fixed an issue where one of the image is not in a container which seems like an oversight to me.

So, I'll keep it open a bit, but if I don't find anything better I'll just close it.

**Comment by doup** [comment]
After the changes to improve the header (#315) I've slightly broken the typography on my branch, which at the same time has broken the features page. Since I need to fix it, I'll improve the code and fix this issue also.

image

**Comment by doup** [comment]
I've fixed this on #315, please take a look at the video.

**Comment by IceSentry** [comment]
This will be fixed by the multiple layout improvements of @doup so I'll close this.

**Pull request closed without merging**
