### PR TITLE
[Merged by Bors] - Enable anchor links in book section

### LINKED ISSUE #274: Turn section header into links
When I try to help people on discord, sometimes I want to link them to specific sections of the website, for example the fast compile setup. It would be much easier if clicking the header would append the css id to the url to make it easier to copy. Or maybe just add a copy button next to the header.

The goal would be to end up with an url like this:
https://bevyengine.org/learn/book/getting-started/setup/#enable-fast-compiles-optional

### PR DESCRIPTION
**Pull request by KDecay**
Enabled the anchor links in every `_index.md` file inside of the `content/learn/book` section.
I ported the changes made in #275 over to the `new_book` branch.

Closes #274 
Closes #275

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@KDecay can you copy over `bors.toml` from `master` so that this works?

**Comment by mockersf** [comment]
bors cancel

**Comment by mockersf** [comment]
canceling to free up bors slot

**Comment by mockersf** [comment]
@KDecay you'll also need the changes from #285

**Pull request closed without merging**
