### PR TITLE
Simplify generate_wasm_examples.sh

### PR DESCRIPTION
**Pull request by SIGSTACKFAULT**
the script was using an unnecessarily convoluted way to clone the bevy repo so i switched it to just `git clone --depth 1`. also added some comments.

(can squash 3aa2 and 3799 if wanted)

### CODE REVIEW

**Comment by rparrett** [comment]
This isn't quite doing the same thing.

`clone_bevy.sh` is getting the `latest` branch. The next parts are retrieving `tools` from the `main` branch.

This is probably still necessary until `0.12` is released.

`clone_bevy.sh` also seems to be used in a few workflows.

**Comment by SIGSTACKFAULT** [comment]
I see. this is my first time with github actions (fluent in gitlab actions) and couldn't tell if `act` was working because the upload jobs at the end always fail locally.

Turns out there's `git clone -b <branch>` which can be used instead of the previous complicated system.

should i start a new MR or just keep adding to this one and squash all my mistakes away?

**Comment by rparrett** [comment]
Feel free to continue here.

**Comment by SIGSTACKFAULT** [comment]
lost the adhd urge so i prolly won't finish this

**Pull request closed without merging**
