### PR TITLE
[Merged by Bors] - Remove Bevy Merch link

### PR DESCRIPTION
**Pull request by cart**
I just pulled my Bevy sweatshirt out of the dryer and the logo has started peeling. Its only been through a wash/dry cycle 3 times now. That is unacceptable. This is the second known case of quality issues with Spring's products (a month ago someone else hit the same issue) and I'm guessing more will start to surface as the products age.

I'm pressed for time atm because I've got a flight to catch tomorrow morning and a wedding celebration all weekend, but I no longer feel comfortable listing this on the home page so I wanted to be proactive here.

When I get back I'll engage with Spring and see if they can make this right (and hopefully resolve the quality issues), but I will almost certainly be looking for alternatives and offering refunds from my own pocket (if Spring won't take responsibility here).

What a bummer.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Oof. That's unfortunate. I think we should remove this ASAP, but I'll leave some time for others to weigh in.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by cart** [comment]
Nah I want this merged now. Better to mitigate damage asap and discuss after the fact.

**Comment by alice-i-cecile** [comment]
Sounds good. That was my instinct, but I realized that you'd just merge it ASAP yourself if you felt this way.

**Pull request closed without merging**
