### PR TITLE
Update local CI running instructions for contributors

### PR DESCRIPTION
**Pull request by TrialDragon**
Before it only had markdownlint, but we've since added djlint and typos, so this needs to be updated.

### CODE REVIEW

**Comment by TrialDragon** [comment]
I can't find an easy way to manually run `editorconfigchecker` outside of CI. Changed the contributing file accordingly.

**Review by BD103 — APPROVED** [review]
This is definitely needed, with all the recent changes.

Consider showing the lint commands as code blocks, so `&&` is not necessary?

```shell
$ markdownlint -f -c --idk-any-options-lol
$ djlint .
$ typos
```

**Comment by TrialDragon** [comment]
The main issue with that is throwing in multi-line command blocks in markdowns numbered lists angers the linters from past experience; AFAIK they can't handle multi-line lists. I will still try tho.

**Comment by TrialDragon** [comment]
Mm, passes CI, but that majorly broke visually, hmm.

**Comment by BD103** [comment]
Looks good! @alice-i-cecile would you mind reviewing if you get the chance?

**Review by alice-i-cecile — APPROVED** [review]

**Pull request merged**
