### PR TITLE
0.14: cover image

### PR DESCRIPTION
**Pull request by cart**

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
I'm content with this. I think it's nice to show off the new features, and I like that there's a repo link. Thanks @IceSentry!

**Review by BD103 — APPROVED** [review]

**Comment by BD103** [comment]
I think I like both the first and second forest shot. I'd prefer to not do foggy square, since it looks dull and less vibrant.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
image


This image by @Jondolf is substantially better: nicer exposure on the sky, better framing, less blinding and shows off the water shader. We should swap to it.

**Comment by cart** [comment]
Yeah I think that one is much better. Currently in the wrong aspect ratio though. I'll see if cropping is reasonable.

**Pull request merged**
