### PR TITLE
0.12 migration: Add view transformations section

### LINKED ISSUE #825: 0.12 Migration: mesh_position_world_to_clip was seemingly removed, but is not mentioned anywhere

### PR DESCRIPTION
**Pull request by rparrett**
Alternative to #826. (See https://github.com/bevyengine/bevy-website/pull/826#issuecomment-1958301010)

Closes #825 
Closes #826

### CODE REVIEW

**Comment by TrialDragon** [comment]
Should add
```md
Closes #825 
Closes #826
```
So that when merged both the issue and alternative PR get closed automatically.

**Comment by rparrett** [comment]
> Should add

Don't think that works with PRs, sadly.

**Comment by TrialDragon** [comment]
> > Should add
> 
> Don't think that works with PRs, sadly.

It does I believe. See the merging of #893 closing #602 as far as i can tell.

**Comment by TrialDragon** [comment]
Should the review comments in the original PR be applied here / solution found here, or should this just be merged as-is with improvements in a follow-up PR like Alice suggested for the original PR?

**Comment by rparrett** [comment]
Would prefer not to dive back into 0.12 rendering breaking changes. Opened this to expedite the process of calling the other PR good enough and getting it merged.

**Review by TrialDragon — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
Merging per the linked PR.

**Pull request merged**
