### PR TITLE
Merge `new-book` into `main`

### LINKED ISSUE #870: Integrate new Bevy book into main
Current plan for integrating new Bevy book into bevy-website/main. Moved from #623 per https://github.com/bevyengine/bevy-website/issues/623#issuecomment-1518887997

- [x] Synchronize `new-book` with `main` to make these changes easier
- [x] #874
- [x] #875
- [x] #876
- [x] #877
- [x] #885 
- [x] #878
- [ ] Merge into main and any final merge conflict resolution not covered in prior PRs

### PR DESCRIPTION
**Pull request by TrialDragon**
Merges the `new-book` branch into `main` resolving conflicts along the way. 

Closes #870 
Closes #602

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Reviewers, I'd like:

1. A quick check that this didn't clobber anything it shouldn't.
2. Local validation using zola that the new book won't be visible to end users.
3. Local validation using zola that contributors can show drafts and check their built pages.

Actual content reviews should wait until we're ready to go live, and be an ongoing process.

**Comment by BorisBoutillier** [comment]
I am kind of new to the website internals so bear with me for my missing knowledge.

_1.  A quick check that this didn't clobber anything it shouldn't._

I have gone through all the sections, on main and in this PR, and I have not found anything missing, but the quick-start replacing the book as expected.

_2.  Local validation using zola that the new book won't be visible to end users._

The new book, is hidden from links, and has the 'hidden' paragraph shown, but can still be accessed with the direct link **URL/learn/book/**, both when serving locally and when creating a build locally. I am not sure if the latter is intended, or if the final web-site is build differently than just `zola build`

_3. Local validation using zola that contributors can show drafts and check their built pages._

I have been able to add a page and show my drafts, but I am not sure I did it the usual expected, I have yet to explicitly contribute pages to the site. a more seasoned contributor should double check this.

I did not use the formal 'review approved' as I feel my yet limited knowledge requires more seasoned/knowledgeable contributors to approve :)

**Review by RomainMazB — CHANGES_REQUESTED** [review]
There are some tiny changes:
- a typo
- some link changes to avoid white blinking due to a redirection for the new quick start url
- codestyle

**But my main concerns are about seo.**
There is a redirection to handle the new url of the quick start, faq and migration guides but it sounds like Zola doesn't create redirection in children pages.

This mean that all the search engine referenced pages under `/learn/book` path, (excluding `/learn/book/quick-start` which is aliased by this PR) will now redirect to a 404.

image
image

I am not sure Zola provides an easy way to handle this.
Solution are:
- code driven: create aliases for each page manually
- server driven: we could create a rules in Nginx(or Apache) to create HTTP 301 redirections

**Comment by RomainMazB** [comment]
@alice-i-cecile My review mostly concern only the first point you wanted to check,
> 1. A quick check that this didn't clobber anything it shouldn't.

For the second point,
> 2. Local validation using zola that the new book won't be visible to end users.

With the actual configuration, it's not totally the case, let me explain.

Even if there is direct internal link to the books, Zola will generate these pages and as confirmed by @BorisBoutillier, they will be accessible for the users who know the direct url.

But our enemy are robots here.
Zola will still integrate these pages into the sitemap.xml file, meaning Google and other search engine will reference these pages and make them visible to the end user.

image

Plus, if we activate the internal Zola search bar, it will display those pages too.

Looking into the Zola documentation and with some local tests, we can fix this using this configuration in the `configuration.toml` file:
```toml
ignored_content = ['*/learn/book/**']
```

But!! Doing so, we break your third concern:
> 3. Local validation using zola that contributors can show drafts and check their built pages.

By adding this configuration, the pages are not generated and the contributors can't see their draft pages anymore.

Not sure how you would tackle this? We can add a notice into the website contributor guide to disable this option in local? Or maybe there is a way with environment variable to let it enable but activate the `ignored_content` only in the CI pipeline?

**Comment by TrialDragon** [comment]
Don't we already hide the public draft pages from the site map like this via robots.txt and disallowing all public draft pages?

**Comment by TrialDragon** [comment]
So, public draft does disallow children in robots.txt, but as Romain has shown stuff was still in sitemap, meaning disallowing isn't removing stuff from sitemap (maybe that isn't how it works to solve the issue? Not sure how that is supposed to work in zola), or public draft code for doing that is flawed. Either way I'm bringing in Romain's solution of marking everything hidden for now since it should work.

**Comment by alice-i-cecile** [comment]
> 1. A quick check that this didn't clobber anything it shouldn't.
Inspecting the diff, this looks good.

> 2. Local validation using zola that the new book won't be visible to end users.

No links are present, and I suspect this shouldn't get hidden.

> 3. Local validation using zola that contributors can show drafts and check their built pages.

This was easy to do by navigating to `http://127.0.0.1:1111/learn/book` after running `zola serve`.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Reviewed and approved by @RomainMazB, as [discussed on Discord](https://discord.com/channels/691052431525675048/695741366520512563/1203801610870988901).

I'm merging this now: follow-up work can be done in other PRs that are less terrible to review.

**Pull request merged**
