### PR TITLE
Write release notes for `KHR_texture_transform` support

### PR DESCRIPTION
**Pull request by janhohenheim**
[Rendered](https://github.com/janhohenheim/bevy-website/blob/main/release-content/0.14/release-notes/11904_Add_support_for_KHR_texture_transform.md)

### CODE REVIEW

**Comment by stan4cb** [comment]
It looks really nice, but I think text and images should be seperated so that layout and theme stuff can do its job.

**Comment by janhohenheim** [comment]
@stan4cb what do you mean by that? I don't understand your feedback.

**Comment by stan4cb** [comment]
My bad, I totally miss the point. I mistakenly considered the renders as the final images.

I guess I wasn't awake enough. Sorry about that!

**Comment by janhohenheim** [comment]
@stan4cb all good :D

**Review by alice-i-cecile — APPROVED** [review]
This really helps contextualize things, thank you!

**Pull request merged**
