### PR TITLE
[Merged by Bors] - Add a dedicated icon for a main branch docs site

### PR DESCRIPTION
**Pull request by james7132**
This adds a PNG icon for denoting the development docs made from bevy's `main` branch. Added as suggested in bevyengine/bevy#3535.

If it doesn't show up in the diff, this is how it looks right now:

image

### CODE REVIEW

**Comment by cart** [comment]
Ultimately I'd like to make a number of changes to this:
* A vector source file (svg) instead of raster (png) to avoid scaling artifacts (the bevy birds have clear scaling artifacts) and get cleaner edges (the border between the hats and the birds is a bit uneven at times)
* Slightly less saturated colors for the text and hats 
* Try the Fira Sans font for the text (which we use for a lot of Bevy content)

I think I'll hold off on merging this until we've iterated a bit, given that we haven't yet published a git version of the docs.

**Comment by james7132** [comment]
Unfortunately, I was not the one who made this (family member of mine did) and there is only a raster available.

Here's the original PSD [file](https://cdn.discordapp.com/attachments/661356651877629982/927649440750272552/icon-with-words-01.psd). The text was done in Adobe Illustrator, but was rasterized upon export to Photoshop.

**Comment by cart** [comment]
Closing for now because I'd like something that stylistically matches the base logo (ideally in svg form).

**Comment by aevyrie** [comment]
bevydev_icon

**Review by IceSentry — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
The fresh icon is nice! A main branch docs site will be very useful, both for development and for testing of new book content per #177.

**Pull request closed without merging**
