### PR TITLE
Reexport oit-demo video

### PR DESCRIPTION
**Pull request by mahulst**
Got an error when running the release notes locally:
image

Reexported the oit-demo video with shotcut, no changes made to the default settings.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
This video was previously failing to work in Firefox, for context. Reviewers: please check it both there and Chrome. Ideally Safari too!

**Comment by mahulst** [comment]
Tested in brave (which is chromium based) and safari too.

**Review by IceSentry — APPROVED** [review]
Works for me, but the original worked for me to 😅

**Comment by rparrett** [comment]
This new export seems significantly lower quality, which makes sense because it was re-encoded to a lower bitrate. (~6k from ~14k)

The new bitrate seems more reasonable, really. Ideally, this would be re-recorded, but the bitrate of the original may be high enough that this doesn't make a huge difference in quality.

I tested on mobile safari and the video seemed to work fine with this PR (and did not work before).

```
Before:
Duration: 00:00:10.83, start: 0.000000, bitrate: 14207 kb/s
Stream #0:0[0x1](und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 14204 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
  
After:
Duration: 00:00:10.84, start: 0.000000, bitrate: 6135 kb/s
Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720, 6121 kb/s, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 15360 tbn (default)
```

**Comment by rparrett** [comment]
Actually, the quality seems lower than expected. I did a re-encode with

```
ffmpeg -i content/news/2024-XX-XX-bevy-0.15/oit-demo.mp4 -vcodec libx264 -vprofile main -preset veryslow -crf 16 -pix_fmt yuv420p oit-yuv420p.mp4
```

Which resulted in a similar bitrate but visibly better quality to my eyes.

https://github.com/user-attachments/assets/2cf863af-70b0-422f-aa98-3df698874950

**Comment by richchurcher** [comment]
> I did a re-encode

This version checks out on various browsers for me.

**Comment by alice-i-cecile** [comment]
@mahulst can you swap the file for the one from @rparrett in this PR and then I'll merge this?

**Comment by cart** [comment]
In the interest of getting things ready asap I swapped the file.

**Pull request merged**
