### PR TITLE
Use pngcrush on all images

### PR DESCRIPTION
**Pull request by msvbg**
I noticed some images were quite big in here. This PR reduces the repo size by about ~156 MB and will probably have a positive impact on bandwidth usage. It's a big PR in terms of files changed, but all I did was to run:

```
find . -type f -iname "*.png" -exec pngcrush -ow {} \;
```

`pngcrush` optimizes the compression settings for png files to minimize file size. It is lossless, so all images should look the same.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Would it be possible to automate this somehow? This seems like a generally useful step we should apply by default.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by msvbg** [comment]
Yeah, it might be possible to set this up as a cron with https://github.com/calibreapp/image-actions or similar.

**Comment by mockersf** [comment]
it should be done before merging png files to the repo, or it will increase the repo size a lot.

I think we were under the impression that Zola automatically compress images when moving them to the built website but I can't find that in the docs

**Review by BD103 — APPROVED** [review]
Looks good, though a few images seem to have increased in size. Do you know why that is?

**Comment by msvbg** [comment]
I think I'll be closing this for now. It'd probably be better to do something more holistic/future-proof here.

**Comment by BD103** [comment]
> > Do you know why that is?
> 
> Not sure, I suppose they were already optimized better without pngcrush.

I don't know if that's true. A significant number of images decreased in file size, I was just curious more than anything.

> I think I'll be closing this for now. It'd probably be better to do something more future-proof here.

I appreciate your concern for this, but I still think this should be merged. If anything is going to be implemented, it will be a request to optimize images _before_ they even get merged into the website. I find it unlikely that existing images will ever be optimized if not done manually.

If you don't have the time to follow through this PR then that's fine, but I still feel this is a valuable improvement. Latency is very important on the web, and decreasing image size is a great way to improve it.

**Pull request closed without merging**
