### PR TITLE
Mention RustRover, an IDE for Rust, in Getting Started

### PR DESCRIPTION
**Pull request by bravit**
Hi! I suggest mentioning RustRover as a dedicated IDE for Rust in the Getting Started docs.

### CODE REVIEW

**Review by MrGVSV — APPROVED** [review]

**Review by BD103 — CHANGES_REQUESTED** [review]
Could you please mention how RustRover is only free under a non-commercial license? I'm not against it being included, but you would not be able to use it if you want to sell your game.

**Comment by mockersf** [comment]
The free licence is only for non-commercial use, so you're not eligible if you intend to sell a game, or receive sponsorship.
Commercial is defined by:
> As per our [license agreement](https://www.jetbrains.com/legal/docs/toolbox/license_non-commercial/), any activity from which you, as a product user, obtain regular direct or indirect income would be classified as commercial usage.

And it's free as in "mandatory telemetry"
> It’s also important to note that if you’re using a non-commercial license, you cannot opt out of the collection of anonymous usage statistics.

**Comment by bravit** [comment]
@BD103 I've mentioned that it is free for non-commercial use. Would it make sense to provide more licensing details on this page?

**Review by BD103 — APPROVED** [review]
I think I'm good with this, thanks!

**Review by SIGSTACKFAULT — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
We shouldn't do this. I have a few arguments for why:

1. RustRover's licensing terms aren't appropriate for our users, either for Bevy engine developers or commercial teams. Only hobbyists can safely use it free, and only if they're okay with telemetry.
2. For beginners who actually need advice on IDE selection, listing multiple options is likely to leave them overwhelmed and confused, rather than presenting a list of options that they can choose between.
3. There's no clear place to draw the line. Why RustRover and VsCode, not VsCodium, Zed, Helix, Sublime Text, Emacs and Vim?

We know that VSCode works well, it's suitable for all of our users, and my dominant concern here is a single, clear path for the new users who need this most.

**Pull request closed without merging**
