### PR TITLE
Vercel Build Script

### PR DESCRIPTION
**Pull request by CooCooCaCha**
This PR adds a custom build script so that vercel correctly compiles bevy assets before running `zola build`.

Use this by changing your vercel build command to `./vercel_build.sh` in your vercel settings
Screenshot 2022-04-05 175027
.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Part of #313.

**Comment by IceSentry** [comment]
So, is that just a vercel feature? Like they look for any `./vercel_build.sh` and run it?

**Comment by CooCooCaCha** [comment]
> So, is that just a vercel feature? Like they look for any `./vercel_build.sh` and run it?

You can actually just change the build command in your settings.

**Comment by IceSentry** [comment]
Oh, that's pretty nice then.

**Comment by mockersf** [comment]
is a custom script also needed to build examples? https://bevyengine.org/examples/

**Comment by CooCooCaCha** [comment]
> is a custom script also needed to build examples? https://bevyengine.org/examples/

Good catch, I didn't know that existed. Working on it.

**Comment by CooCooCaCha** [comment]
Updated the script to compile bevy examples. You can check it here https://bevy-website-hd0mg2wxd-wrjstuff.vercel.app/examples

Compiling examples also bumped up the build time to 9min 20s.

**Comment by IceSentry** [comment]
Since it's for dev branches and quick iterations, could we skip the examples? It's a bit long especially if most of the dev work won't be on that page.

**Comment by CooCooCaCha** [comment]
> Since it's for dev branches and quick iterations, could we skip the examples? It's a bit long especially if most of the dev work won't be on that page.

Not a bad idea. I'll leave the decision up to someone higher up the chain.

For the record the base website takes about 10s to build. With assets 1min 12s. With examples 9min 20s.  

Something we could do in the future is move examples to a separate repo and pre-build assets and examples. That way building the website (for prod and dev) would be super fast.

**Comment by alice-i-cecile** [comment]
> Not a bad idea. I'll leave the decision up to someone higher up the chain.

I'd prefer to skip examples: they're rarely going to be relevant to this repo and the added friction is high enough that I'd prefer to just skip them.

> Something we could do in the future is move examples to a separate repo and pre-build assets and examples. That way building the website (for prod and dev) would be super fast.

Agreed here. It would also be *very* interesting to have web-available examples for each `bevyengine/bevy` PR to allow reviewers to quickly test out relevant functionality.

**Comment by mockersf** [comment]
Can the example be built conditionally if the relevant css/html files are modified?

Or can the page be built without building the wasm, including a dummy content? The example pages are currently in dire need of a better style and more presence on the site

**Comment by CooCooCaCha** [comment]
> Can the example be built conditionally if the relevant css/html files are modified?
> 
> Or can the page be built without building the wasm, including a dummy content? The example pages are currently in dire need of a better style and more presence on the site

I'm still figuring out how all that works but perhaps we could add a flag to the examples build script that skips the wasm step? Theoretically, the pages would still work but the examples themselves would appear blank.

In a followup PR we could do something more elegant like replace the examples with placeholders.

**Comment by CooCooCaCha** [comment]
Ok I updated the script to disable WASM compilation only for vercel builds. 
This brings the compilation time to around 1min 30s. 

When WASM is disabled it just shows a blank space on the page as can be seen here: https://bevy-website-55e99xe2w-wrjstuff.vercel.app/examples

In the future we could potentially use git to see if any WASM files have changed and conditionally set the SKIP_WASM flag.

**Review by IceSentry — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
We got ghosted on some of our questions, so I'm going to close this out and we'll go with a competitor...

**Comment by cart** [comment]
In fairness I was the one that ghosted them right after they called out that we can deploy without their "overly permissioned" github integration by using their CLI. There is a chance we can still make this work, although idk if we could make the user experience great without writing additional automation to "close the loop" by somehow getting the preview url from the CLI and having a bot leave it in a comment on the relevant pr.

**Comment by alice-i-cecile** [comment]
Ah, fair enough. All the same, I think I'd rather poke at Netlify's version of this feature rather than sinking more time in here.

**Pull request closed without merging**
