### PR TITLE
[Merged by Bors] - Add MSRV to setup guide

### PR DESCRIPTION
**Pull request by IceSentry**
Add a short text describing bevy's MSRV policy. Uses the same text that is in the migration guides

Closes https://github.com/bevyengine/bevy-website/issues/467

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by ickk — APPROVED** [review]
Given some of the audience could be pretty new to the rust ecosystem, I think it could be helpful to add some actionable language here: i.e. "When installing or updating Bevy be sure to run `rustup update` to ensure you have the latest version of the Rust toolchain".

**Comment by alice-i-cecile** [comment]
Agreed with Nick there; I'd like to see that before merging.

**Comment by IceSentry** [comment]
I didn't include it because the next paragraph points people to rust's official getting started guide which already explains this.

**Pull request closed without merging**
