### PR TITLE
Fix On This Page algorithm

### PR DESCRIPTION
**Pull request by SIGSTACKFAULT**
scope-creep edition!

- sort by the actual Y position. and not the top border width.
- sort in the correct direction
- handle the case where there are no `<h2>`s (which is the case on migration guides)
- compare `<a href>` which need to be there anyway instead of `<li data-fragment>`

### CODE REVIEW

**Review by TrialDragon — APPROVED** [review]
LGTM. Tho why do we use `<h3>` instead of `<h2>` as the next step down from a `<h1>` in the migration guides I wonder. Semantically weird, and style-wise a `<h2>` can be styled to look correctly.

**Comment by IceSentry** [comment]
>  Tho why do we use <h3> instead of <h2>

The code from that is pretty old, so my guess is just that cart liked the look of a h3 better and nobody questioned it since, but yeah, we should just use h2 and update the styling

**Comment by SIGSTACKFAULT** [comment]
scope creep >.<

**Review by TrialDragon — APPROVED** [review]

**Comment by SIGSTACKFAULT** [comment]
Will rebase when I get home tomorrow

**Comment by SIGSTACKFAULT** [comment]
Also request from @Jondolf because after rebasing i had to mess with your styles

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@SIGSTACKFAULT once merge conflicts are resolved I'll merge this in for you.

**Comment by SIGSTACKFAULT** [comment]
@alice-i-cecile resolved!

**Pull request merged**
