### PR TITLE
Small update on base.html

### PR DESCRIPTION
**Pull request by shirshak55**
- [x] Remove Unnecessary space
- [x] Add html5 support tag so it doesn't show red when you open view page source :D

### CODE REVIEW

**Comment by cart** [comment]
I dig adding the support tag, but I'm not sure removing the space is an improvement. The space helps you visually parse sets of if statements. Removing the space makes it look like one big blob imo. Can you update the pr to only add the support tag?

**Comment by shirshak55** [comment]
@cart Is it ok now?

**Comment by cart** [comment]
Just removed the weird `-` that were added. now its good to go.

**Comment by shirshak55** [comment]
that weird - just don't allow new lines :)  Anyway if you are fine I thing we are ok with it 💯

**Pull request merged**
