### PR TITLE
[Merged by Bors] - add .vscode to gitignore

### PR DESCRIPTION
**Pull request by IceSentry**
I have a few extensions causing me problem in this repo and I like disabling them in a vscode/settings.json

Since main bevy already has that ignore I feel it's ok to also add it here.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Merging as trivial.

bors r+

**Comment by Nilirad** [comment]
I don't like this. It's better that the PR author instead ignores editor specific files on their end instead of requesting a change in every project they contribute to.

**Comment by TimJentzsch** [comment]
You can do this by setting a global gitignore file: <https://stackoverflow.com/a/7335487>

**Comment by Nilirad** [comment]
I recognize though that it could be beneficial for the project to ignore common files, for user friendliness.

**Comment by alice-i-cecile** [comment]
I decided to opt for user friendliness and consistency with the main repo here :) I think your solution is more correct, but I want to make sure novices can participate with a minimum amount of yak shaving.

**Pull request closed without merging**
