### PR TITLE
[Merged by Bors] - Enable anchors on links in learn section

### LINKED ISSUE #274: Turn section header into links
When I try to help people on discord, sometimes I want to link them to specific sections of the website, for example the fast compile setup. It would be much easier if clicking the header would append the css id to the url to make it easier to copy. Or maybe just add a copy button next to the header.

The goal would be to end up with an url like this:
https://bevyengine.org/learn/book/getting-started/setup/#enable-fast-compiles-optional

### PR DESCRIPTION
**Pull request by mockersf**
Fixes #274

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Ooh nice.

**Review by rparrett — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]
Well, that was a fast turn around between creating an issue and having a solution.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
bors setup is not correct and will timeout, see https://github.com/bevyengine/bevy-website/pull/285

**Comment by mockersf** [comment]
bors cancel

**Comment by mockersf** [comment]
(not sure bors will be happy here or if it need a rebase)

**Pull request closed without merging**
