### PR TITLE
[Merged by Bors] - Improve example page

### PR DESCRIPTION
**Pull request by doup**
- This doesn't change the listing layout, **but** improves the sidebar category labels
  - Tweaks example generation script to include labels for categories instead of using folder name
- Tweak single example page layout

image

image

image

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@cart should we have an `A-Examples` tag? It really doesn't fit in well anywhere.

**Review by mockersf — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@doup this is still a draft; is there anything else you want to tackle before we merge this?

**Comment by doup** [comment]
I left this as a draft as I noticed that BevyMark isn't loading (see #351). But that's already a prod issue and can be tackled on another PR. So marking this as "ready for review".

**Comment by alice-i-cecile** [comment]
bors retry

**Comment by cart** [comment]
Just wanted to swing by and say that this was really well done. Feels very polished!

**Pull request closed without merging**
