### PR TITLE
[Merged by Bors] - Update setup instructions for bevy 0.7

### PR DESCRIPTION
**Pull request by futile**
Since bevy 0.7 is released, change the mentioned versions in the setup instructions from 0.6 to 0.7.

### CODE REVIEW

**Review by cart — APPROVED** [review]
Good call. Thanks!

**Comment by futile** [comment]
Anything I missed or is CI just having some troubles?

**Comment by mockersf** [comment]
this should be fixed by #341

**Comment by futile** [comment]
Ok, will rebase when that is merged :)

**Pull request closed without merging**
