### PR TITLE
Phase 1 of Contributor's Guide – Foundational Folder

### PR DESCRIPTION
**Pull request by TrialDragon**
A part of #1146

A simple public draft folder like the Bevy Book's folder that the rest of the Contributor's Guide content can be put into as each phase commences.

### CODE REVIEW

**Review by NthTensor — APPROVED** [review]

**Comment by NthTensor** [comment]
First working group PR :1st_place_medal:

**Review by BD103 — APPROVED** [review]
Awesome, let's get the ball rolling!

**Review by SIGSTACKFAULT — APPROVED** [review]

**Comment by SSebigo** [comment]
So now that the book is created, do we wait for this PR to be merged to add the content? Or do we make PRs into @TrialDragon fork?
Sorry if it's a dumb question, I'm new to open source contributions.

**Comment by NthTensor** [comment]
I think probably we will merge this an open separate PRs for each section. This work is being coordinated by a [working group](https://github.com/bevyengine/bevy/blob/main/CONTRIBUTING.md#join-a-working-group) in the [bevy discord](https://discord.com/invite/bevy) which I encourage you to join @SSebigo!

**Pull request merged**
