### PR TITLE
fix code highlighting after zola 0.14

### PR DESCRIPTION
**Pull request by mockersf**
- move the config option to the correct section
- fix the background color

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by cart** [comment]
Merged asap because some highlighting is better than no highlighting. Just got my local zola updated. And now I want to tweak this a bit :smile: 

Heres a quick / rough comparison:

image

1. right: old
2. top left: new (with new css tweaks to revert the background to the old color)
3. bottom left: current main with new background color

My preference is (1), (2), (3). I think (3)'s background sticks out too much. (2) has regrettably lost a lot of contrast compared to (1). I'd like the colors to pop more if possible (like the do in (1)).

I suspect i'll be messing around with this for awhile :)

**Comment by cart** [comment]
Here is (2) again with the background colors properly synced up:
image

**Comment by cart** [comment]
Note how bland it looks now :sob:

**Comment by cart** [comment]
Good news! The new release has lots of configuration options. We can now build fully custom css themes: https://www.getzola.org/documentation/content/syntax-highlighting/

**Comment by cart** [comment]
(which i will absolutely do)

**Comment by mockersf** [comment]
> (which i will absolutely do)

That... doesn't surprise me at all from you 👍

**Pull request merged**
