### PR TITLE
[Merged by Bors] - Replace book pager with prev/next buttons & "improve this page" link

### PR DESCRIPTION
**Pull request by doup**
- Replace book pager with a couple of footer prev/next buttons.
  - The main reason is that the current "previous" pager doesn't play nicely with the book menu. Also this proposal works better on mobile and gives extra info on what's next/previous.
- Add "Improve this page" link to GitHub

image

image

https://user-images.githubusercontent.com/188612/162803760-aa7387ea-188f-4c83-bbd5-a36914d8cae3.mp4

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I like the Improve This Page idea!

And yeah, those previous buttons were a bit buggier than I'd like :(

**Comment by cart** [comment]
Yeah I love all of the ideas + improvements you've been bringing to the table. These changes are awesome.

**Comment by doup** [comment]
Just a minor update, I've added an `icon` component which allows to change SVG color via CSS `color` or `background-color`. This is to avoid doing `hover` color changes using `opacity`; eventually will be easier to migrate to a color palette if proper colors are used.

Oh! And now there is a pencil icon for the page editing. ☺️ 

https://user-images.githubusercontent.com/188612/163245874-57c939a6-8eb5-41fe-ae8a-909fe5ad63d9.mp4

**Comment by cart** [comment]
Played a bit more with this and I think its worth merging asap for the 0.7 release. Really steps up the perceived quality of the book. This does currently break keyboard navigation though. If you can fix that (its done in the `optional-helpers.js` file using simple element selection by id), I'll merge this asap.

**Comment by doup** [comment]
Ops, I saw that… but then forgot about it. 😅 
I've fixed it on the last commit.

**Comment by alice-i-cecile** [comment]
Keyboard navigation and layout are working for me :D

However, the chevrons aren't showing up properly on my local build:
image

IDK if that's just git weirdness though.

**Comment by doup** [comment]
Now it should be fixed, sorry I didn't check on Chrome/Safari (shame). ^_^U

**Comment by alice-i-cecile** [comment]
Fixed for me now!

**Pull request closed without merging**
