### PR TITLE
Merge master to new-book branch

### PR DESCRIPTION
**Pull request by IceSentry**
There's been a lot of good stuff added to master since the creation of this branch.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Good call!

**Comment by ickk** [comment]
I'm not quite sure how git handles this. Might it make more sense to rebase `new-book` on `master`?

When we eventually merge new-book into master later, will we squash the commits in new-book?

**Comment by alice-i-cecile** [comment]
> When we eventually merge new-book into master later, will we squash the commits in new-book?

By default, but Cart can override this.

**Comment by cart** [comment]
Adding new commits like this and using bors for a merge  / squashing them together will make this commit pretty nasty. We should consider a manual merge here to help git reason about the history.

**Comment by cart** [comment]
@alice-i-cecile when you think this is ready let me know and I can temporarily enable "normal merge commits" and press the merge button.

**Comment by alice-i-cecile** [comment]
Sounds good. Once CI is passing this is good to merge.

@IceSentry let us know when that's ready :)

**Comment by IceSentry** [comment]
@alice-i-cecile I think it's ready now. I manually fixed the lints and now CI passes. (manually being hitting ctrl-s in vscode and letting markdownlint do it's job 😅)

**Comment by alice-i-cecile** [comment]
Ping @cart for manual merge please.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by cart** [comment]
Done!

**Pull request merged**
