### PR TITLE
Update quick start guide & learning-code-examples to reference 0.15 instead of 0.14

### LINKED ISSUE #1917: Quick-start guide still references bevy 0.14
Quick start guide still references bevy 0.14 in places. Specifically [here](https://bevyengine.org/learn/quick-start/getting-started/#add-bevy-as-a-dependency) and [here](https://bevyengine.org/learn/quick-start/getting-started/setup/#add-bevy-as-a-dependency).

### PR DESCRIPTION
**Pull request by fallible-algebra**
Not much to this, just an update from bevy `0.14` to `0.15` in the quick start guide & `learning-code-examples` folder.

This touches the `Cargo.lock`, so if that's an issue I'd be happy to override this with a change that just touches the quick start guide.

Fixes #1917

### CODE REVIEW

**Comment by fallible-algebra** [comment]
Opened an issue [here](https://github.com/bevyengine/bevy-website/issues/1917) and will be modifying the commit message to reference it.

**Review by kristoff3r — APPROVED** [review]

**Review by cart — APPROVED** [review]
Thanks! I reverted the cargo.lock changes as they're hard to verify and have security implications iirc.

**Comment by cart** [comment]
@fallible-algebra fyi if a PR resolves an issue, edit the description with `Fixes #ISSUE_NUMBER` and it will auto-close that issue on merge.

**Comment by fallible-algebra** [comment]
> @fallible-algebra fyi if a PR resolves an issue, edit the description with `Fixes #ISSUE_NUMBER` and it will auto-close that issue on merge.

Cheers, I'm still getting used to this kind of collaboration and workflow 🙂

**Pull request merged**
