### PR TITLE
Update optimization suggestions based on benchmark

### PR DESCRIPTION
**Pull request by benfrankel**
Data thanks to @rparrett:

https://github.com/rparrett/bevy_wasm_bench/blob/main/results/d98b3a8_win11_i713700KF_4080super.csv

### CODE REVIEW

**Comment by benfrankel** [comment]
Some additional thoughts:

> Interestingly `codegen-units=1` doesn't seem to do much besides increase compile times if you already enabled `lto`
> Maybe it shouldn't be recommended at all
> Or that might be overfitting to the benchmark

A quick search actually found discussions suggesting the _opposite_ behavior, so I left `codegen-units=1` in.

**Comment by benfrankel** [comment]
As for `opt-level`, `z` significantly reduces file size compared to `s`, but it also significantly reduces runtime performance. `s` should be a more balanced option to suggest by default.

**Comment by tbillington** [comment]
With LTO & wasm-opt the size is already pretty good. The savings of s/z over 2/3 don't tend to be that meaningful. In a context where the user is already downloading a 15mb wasm blob, potentially having a few more mb is worth it for better performance, imho. We're already running in a resource constrained environment, so hamstringing optimisations is not desirable.

Just my 2c :)

**Comment by rparrett** [comment]
Just making a note that I am not sure how much my data generalizes to
- other targets
- other hardware
- other browsers
- other workloads
- etc

And there wasn't a whole lot of scientific rigor involved in testing to begin with.

I gathered the data because I couldn't find any real information about how various file-size-focused optimizations affected runtime performance in the browser.

My takeaway for this particular setup was
- `opt-level = "z"` costs too much performance, I'd rather accept slightly larger files.
- `lto = "thin"` seems to give more than a "marginal" boost: ~10%. But the compile time cost is significant.

But there are various tradeoffs so people should just know that they might want to fiddle with this stuff and do their own measurements.

**Comment by benfrankel** [comment]
> With LTO & wasm-opt the size is already pretty good. The savings of s/z over 2/3 don't tend to be that meaningful.

While I agree in concept, it should be noted that `-Os` isn't really losing runtime performance compared to `-O3`; in this benchmark at least.

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Pull request merged**
